server:
  port: 6060

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AuthAracDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
